# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: ls -1d services/*/ | xargs -I {} swift build -v --package-path {}
    - name: Run tests
      run: ls -1d services/*/ | xargs -I {} swift test -v --package-path {}
